version: '3.8'

services:
  mysql:
    image: mysql:8
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MYSQL_DATABASE: "directus"
      MYSQL_USER: "directus_user"
      MYSQL_PASSWORD: "directus_password"
    ports:
      - "5101:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s

  directus:
    image: directus/directus:latest
    ports:
      - "8055:8055"
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    environment:
      KEY: "mysecretkey"
      SECRET: "mysecret"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "admin"
      DB_CLIENT: "mysql"
      DB_HOST: "mysql"
      DB_PORT: "3306"
      DB_DATABASE: "directus"
      DB_USER: "directus_user"
      DB_PASSWORD: "directus_password"

volumes:
  mysql_data: